name: searchengine
description: A simple search engine app using Flutter and Kotlin
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add core dependencies
  cupertino_icons: 1.0.5
  async: 2.11.0
  boolean_selector: 2.1.1
  characters: 1.4.0
  clock: 1.1.2
  collection: 1.19.1
  matcher: 0.12.17
  meta: 1.16.0
  path: 1.9.1
  stream_channel: 2.1.4
  vector_math: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  fake_async: 1.3.3
  leak_tracker: 11.0.2
  leak_tracker_flutter_testing: 3.0.10
  leak_tracker_testing: 3.0.2
  test_api: 0.7.6

flutter:
  uses-material-design: true
